# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-app.fullname" . }}
  labels:
    app: {{ include "example-app.name" . }}
    chart: {{ include "example-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "example-app.name" . }}
    release: {{ .Release.Name }}
